import { CentralSignal, MarketData, OnChainData, RegimeWeights, AgentSignal, TradeAction } from './types';
import { MarketRegimeDetector } from './regimeDetector';
import { TrendAgent } from './agents/trendAgent';
import { MeanReversionAgent } from './agents/meanReversionAgent';
import { MomentumAgent } from './agents/momentumAgent';
import { NewsAgent } from './agents/newsAgent';

/**
 * The Orchestrator coordinates the market regime detection and coordinates signals
 * across all specialist trading agents. It acts as the central intelligence of the system.
 */
export class Orchestrator {
  private regimeDetector: MarketRegimeDetector;
  private trendAgent: TrendAgent;
  private meanReversionAgent: MeanReversionAgent;
  private momentumAgent: MomentumAgent;
  private newsAgent: NewsAgent;
  
  public latestRegimeResult: any = null;

  /**
   * Initializes the Orchestrator with instances of all specialist agents and the regime detector.
   */
  constructor() {
    this.regimeDetector = new MarketRegimeDetector();
    this.trendAgent = new TrendAgent();
    this.meanReversionAgent = new MeanReversionAgent();
    this.momentumAgent = new MomentumAgent();
    this.newsAgent = new NewsAgent();
  }

  /**
   * Orchestrates the full analysis pipeline:
   * 1. Detects the current market regime and gets capital weights.
   * 2. Triggers signal generation from all active specialist agents.
   * 3. Aggregates individual agent signals weighted by the regime allocation.
   * 
   * @param marketData - Current market price data
   * @param onChainData - On-chain indicators (Dune Analytics)
   * @param historicalCandles - Price history (used by technical agents)
   * @param newsHeadlines - Market news (used by the news agent)
   * @returns A promise resolving to the final combined trade recommendation
   */
  async runPipeline(
    marketData: MarketData,
    onChainData: OnChainData,
    historicalCandles: any[],
    newsHeadlines: string[]
  ): Promise<CentralSignal> {
    console.log('Orchestrator: Executing central intelligence pipeline...');

    // 1. Detect market regime
    const regimeResult = await this.regimeDetector.detectRegime(marketData, onChainData);
    this.latestRegimeResult = regimeResult;
    console.log(`Orchestrator: Detected Regime is "${regimeResult.regime}" with weights:`, JSON.stringify(regimeResult.weights, null, 2));

    // Retrieve active market price from candles if marketData price is empty
    const currentPrice = marketData.price || (historicalCandles.length > 0 ? parseFloat(historicalCandles[historicalCandles.length - 1][4]) : 0);
    const updatedMarketData: MarketData = { ...marketData, price: currentPrice };

    // 2. Fetch current funding rate for the news agent
    let fundingRate = regimeResult.marketSnapshot?.fundingRate || 0.0;

    // 3. Trigger signal generation across all agents in parallel
    console.log('Orchestrator: Emitting signals to Trend, Mean Reversion, Momentum, and News Agents...');
    const [trendSig, meanRevSig, momentumSig, newsSig] = await Promise.all([
      this.trendAgent.generateSignal(updatedMarketData, historicalCandles),
      this.meanReversionAgent.generateSignal(updatedMarketData, historicalCandles),
      this.momentumAgent.generateSignal(updatedMarketData, historicalCandles),
      this.newsAgent.generateSignal(updatedMarketData, newsHeadlines, { fundingRate, regime: regimeResult.regime })
    ]);

    const signals = [trendSig, meanRevSig, momentumSig, newsSig];
    console.log('Orchestrator: Agent signals received:');
    signals.forEach(s => {
      console.log(` - [${s.agentId}]: ${s.action} (Confidence: ${(s.confidence * 100).toFixed(1)}%)`);
    });

    // 4. Aggregate signals based on regime weights
    const centralSignal = this.aggregateSignals(signals, regimeResult.weights);
    console.log(`Orchestrator: Formulated Central Signal: ${centralSignal.action} (Weighted Confidence: ${(centralSignal.confidence * 100).toFixed(1)}%)`);

    return centralSignal;
  }

  /**
   * Combines individual agent recommendations into a single weighted action and confidence score.
   * 
   * @param signals - Array of signals generated by the specialist agents
   * @param weights - Active capital weights calculated by the regime detector
   * @returns The aggregated trade action and weighted confidence
   */
  private aggregateSignals(
    signals: AgentSignal[],
    weights: RegimeWeights
  ): CentralSignal {
    const timestamp = new Date().toISOString();

    // Mapping agent IDs to their respective regime weights
    const weightMap: { [key: string]: number } = {
      trend_agent: weights.trendAgent,
      mean_reversion_agent: weights.meanReversionAgent,
      momentum_agent: weights.momentumAgent,
      news_agent: weights.newsAgent
    };

    let weightedScoreSum = 0;
    let confidenceSum = 0;

    for (const signal of signals) {
      const weight = weightMap[signal.agentId] ?? 0.25;
      
      // Convert action to numerical value: BUY = +1, SELL = -1, HOLD = 0
      let numericAction = 0;
      if (signal.action === 'BUY') {
        numericAction = 1;
      } else if (signal.action === 'SELL') {
        numericAction = -1;
      }

      // Add to weighted score: Weight * Confidence * Action Value
      weightedScoreSum += weight * signal.confidence * numericAction;
      
      // Cumulative confidence: Weight * Confidence
      confidenceSum += weight * signal.confidence;
    }

    // Determine target action based on weighted score
    // Thresholds: score > 0.2 = BUY, score < -0.2 = SELL, else HOLD
    let action: TradeAction = 'HOLD';
    if (weightedScoreSum > 0.2) {
      action = 'BUY';
    } else if (weightedScoreSum < -0.2) {
      action = 'SELL';
    }

    return {
      action,
      confidence: Math.min(1.0, Math.max(0.0, confidenceSum)),
      agentSignals: signals,
      timestamp
    };
  }
}
