/**
 * Market regimes that the system can classify.
 */
export type MarketRegime = 'Trending' | 'Sideways' | 'Volatile';

/**
 * Capital weight allocation for the specialist trading agents.
 * Sum of these weights must equal 1.0.
 */
export interface RegimeWeights {
  trendAgent: number;
  meanReversionAgent: number;
  momentumAgent: number;
  newsAgent: number;
}

/**
 * Standard trading actions a signal can recommend.
 */
export type TradeAction = 'BUY' | 'SELL' | 'HOLD';

/**
 * Represents a trading signal generated by a specialist agent.
 */
export interface AgentSignal {
  agentId: string;
  action: TradeAction;
  confidence: number; // Value between 0.0 (no confidence) and 1.0 (maximum confidence)
  reasoning: string;  // Plain English reasoning for the generated signal
  timestamp: string;  // ISO timestamp of signal generation
}

/**
 * Aggregated trade recommendation computed by the central Orchestrator.
 */
export interface CentralSignal {
  action: TradeAction;
  confidence: number;             // Weighted confidence score
  agentSignals: AgentSignal[];    // Raw signals from the active specialist agents
  timestamp: string;              // ISO timestamp of orchestration
}

/**
 * Market data inputs used by agents and the regime detector.
 */
export interface MarketData {
  symbol: string;
  price: number;
  high24h?: number;
  low24h?: number;
  volume24h?: number;
  timestamp: string;
}

/**
 * On-chain metrics retrieved from Dune Analytics.
 */
export interface OnChainData {
  btcDominance?: number;
  stablecoinSupply?: number;
  gasPriceGwei?: number;
  timestamp: string;
}

/**
 * Represents a position held in paper trading.
 */
export interface Position {
  symbol: string;
  side: 'long' | 'short';
  amount: number;
  entryPrice: number;
  unrealizedPnl: number;
}
